export const styles = {
  topContainer: {
    display: "flex",
    flexDirection: "row",
    overflow: 'auto'
  },
  toph1: {
    color: "red",
  },
  backg: {
    backgroundColor: "#1A374D",
  },
  button: {
    display: "inline-block",
    padding: 10,
    border: 0.1,
    borderRadius: 12,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: "#B85252",
    fontSize: 25,
    color: "#000000",
    cursor: "pointer",
    width: 200,
    height: 60,
  },
  button1: {
    display: "inline-block",
    padding: 10,
    margin: 30,
    border: 0.1,
    borderRadius: 12,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: "#ff0066",
    fontSize: 20,
    color: "#ffffff",
    cursor: "pointer",
    width: 150,
    height: 50,
  },
  poster_button: {
    color: "white",
    backgroundColor: "transparent",
    cursor: "pointer",
    borderColor: "transparent",
  },
  modalbtn: {
    color: "white",
    backgroundColor: "#ff0066",
    cursor: "pointer",
    opacity: 0.8,
    borderColor: "#ff0066",
    height: 50,
    width: 200,
    fontSize: 25,
  },
  title: {
    fontFamily: "Roboto",
    fontSize: 52,
    color: "#FF5959",
    textAlign: "center",
  },
  details: {
    padding: 30,
    color: "#FF5959",
    fontSize: 15,
  },
  details_title: {
    color: "white",
    fontSize: 20,
    paddingRight: 100,
    fontWeight: "bold",
  },
  AddMovieBox: {
    width: 200,
    height: 30,
    fontSize: 20,
    borderRadius: 10,
    borderColor: "#FF5959",
  },
};
